### ISSUE TITLE
Inserire elenco definzioni in about per i nostri nomi e descrizioni

### ISSUE THREAD

**Issue by mveronesi** [LeonardoTredese/annoiato#10]

**Comment by LeonardoTredese** [comment]
nel caso qualcuno cercasse i nostri nomi?

**Comment by mveronesi** [comment]
Si presta ad essere un DL secondo me, alla fine è un elenco con titolo e descrizione

**Comment by SamueleVanini** [comment]
Se volete parlarne qui (#8 ) che oltre a questo c'è un'altra cosa modificabile passando ad html5

**Comment by rizzostefano** [comment]
Sono del parere che fare una definition list non sia una soluzione pulita. Per gestire il ridimensionamento per i dispositivi mobili ed il crop delle immagini sono necessari dei div che dovrebbero essere necessariamente portati all'interno della definition list, rendendo di fatto inutile il possibile vantaggio in pulizia e separazione contenuto/presentazione.
