### ISSUE TITLE
Convertire in HTML 5

### ISSUE THREAD

**Issue by mveronesi** [LeonardoTredese/annoiato#8]

**Comment by SamueleVanini** [comment]
Il grosso del porting è stato fatto, inoltre sono anche già state validate tutte le pagine presenti (al momento del commit 884df5834d6d835a02f870f28b20cba801e6c757) per questo ho ritenuto che la issue #7 non avesse senso di essere ancora aperta. Mancano ancora alcuni dettagli, ovvero, l'utilizzo di un elenco di definizioni (o non so cos'altro) per le nostre descrizioni in about e se cambiare in una section il div con classe wrapper all'interno dei pageFooter.
